#pragma once
enum class MessageID
{

	MSG_UNKNOWN,
	MSG_DESTROY_ENTITY,
	MSG_CREATE_PROJECTILE,
	MSG_CREATE_SPRAY,
	MSG_CREATE_HAWK,
	MSG_CHANGE_LEVEL,
	MSG_CREATE_GRAVPROJECTILE,
	MSG_CREATE_HORIZ_BUBBLE,
	MSG_CREATE_VERT_BUBBLE,
	MSG_CREATE_VOMIT,
	MSG_CREATE_POOP,
	MSG_CREATE_STALACTITE,
};

